GET http://localhost:8080/api/employees/

###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker"
}

###
DELETE http://localhost:8080/api/employees/637e22ce74045fd928489109

###
PATCH http://localhost:8080/api/employees/637e22ce74045fd928489109
Content-Type:  application/json

{
  "name": "Adam"
}
